### ISSUE TITLE
Unable to connect to unifi 

### ISSUE THREAD

**Issue by snoekieboe** [i8beef/HomeAutio.Mqtt.UnifiVideo#1]
Help, i'm having troubles settings this up.

I've started a container using your latest version.. configured appsettings.json and restarted the container but it's throwing the following errors:

ndled Exception: System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.PostAsync(Uri requestUri, HttpContent content, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.AuthorizeAsync(CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.GetAsync(String relativeUrl, IEnumerable`1 queryParams, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.CameraAsync(String cameraId, CancellationToken cancellationToken)

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.GetInitialStatusAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 151

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.StartServiceAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 63

   at HomeAutio.Mqtt.Core.ServiceBase.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at HomeAutio.Mqtt.UnifiVideo.Program.MainAsync(String[] args) in /app/HomeAutio.Mqtt.UnifiVideo/Program.cs:line 52

   at HomeAutio.Mqtt.UnifiVideo.Program.Main(String[] args) in /app/HomeAutio.Mqtt.UnifiVideo/Program.cs:line 23

[21:05:41 INF] Service start initiated

[21:05:41 INF] MQTT subscribing to the following topics: unifi/video/default/camera/+/+/set

[21:05:42 INF] Started

[21:05:42 FTL] An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.PostAsync(Uri requestUri, HttpContent content, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.AuthorizeAsync(CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.GetAsync(String relativeUrl, IEnumerable`1 queryParams, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.CameraAsync(String cameraId, CancellationToken cancellationToken)

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.GetInitialStatusAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 151

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.StartServiceAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 63

   at HomeAutio.Mqtt.Core.ServiceBase.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at HomeAutio.Mqtt.UnifiVideo.Program.MainAsync(String[] args) in /app/HomeAutio.Mqtt.UnifiVideo/Program.cs:line 52

Unhandled Exception: System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.PostAsync(Uri requestUri, HttpContent content, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.AuthorizeAsync(CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.GetAsync(String relativeUrl, IEnumerable`1 queryParams, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.CameraAsync(String cameraId, CancellationToken cancellationToken)

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.GetInitialStatusAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 151

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.StartServiceAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 63

   at HomeAutio.Mqtt.Core.ServiceBase.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at HomeAutio.Mqtt.UnifiVideo.Program.MainAsync(String[] args) in /app/HomeAutio.Mqtt.UnifiVideo/Program.cs:line 52

   at HomeAutio.Mqtt.UnifiVideo.Program.Main(String[] args) in /app/HomeAutio.Mqtt.UnifiVideo/Program.cs:line 23

[21:06:42 INF] Service start initiated

[21:06:42 INF] MQTT subscribing to the following topics: unifi/video/default/camera/+/+/set

[21:06:42 INF] Started

[21:06:42 FTL] An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.PostAsync(Uri requestUri, HttpContent content, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.AuthorizeAsync(CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.GetAsync(String relativeUrl, IEnumerable`1 queryParams, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.CameraAsync(String cameraId, CancellationToken cancellationToken)

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.GetInitialStatusAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 151

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.StartServiceAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 63

   at HomeAutio.Mqtt.Core.ServiceBase.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at HomeAutio.Mqtt.UnifiVideo.Program.MainAsync(String[] args) in /app/HomeAutio.Mqtt.UnifiVideo/Program.cs:line 52

Unhandled Exception: System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.PostAsync(Uri requestUri, HttpContent content, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.AuthorizeAsync(CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.GetAsync(String relativeUrl, IEnumerable`1 queryParams, CancellationToken cancellationToken)

   at I8Beef.UniFi.Video.Client.CameraAsync(String cameraId, CancellationToken cancellationToken)

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.GetInitialStatusAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 151

   at HomeAutio.Mqtt.UnifiVideo.UniFiVideoMqttService.StartServiceAsync(CancellationToken cancellationToken) in /app/HomeAutio.Mqtt.UnifiVideo/UniFiVideoMqttService.cs:line 63

   at HomeAutio.Mqtt.Core.ServiceBase.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at HomeAutio.Mqtt.UnifiVideo.Program.MainAsync(String[] args) in /app/HomeAutio.Mqtt.UnifiVideo/Program.cs:line 52

   at HomeAutio.Mqtt.UnifiVideo.Program.Main(String[] args) in /app/HomeAutio.Mqtt.UnifiVideo/Program.cs:line 23

**Comment by i8beef** [comment]
That should be be `appsettings.Production.json`. The error indicates your unifiHost is not a full URI, like `https://1.1.1.1:7443`. That could be because your settings are wrong, or it didn't read the `appsettings.Production.json` file to override the default.

**Comment by snoekieboe** [comment]
It’s working now.

I did not create the directory and json file before creating the container. this resulted in docker mounting app settings.Production.json as a directory instead of a file.

Thanks!

Br

Roel

**Comment by i8beef** [comment]
Ah, yeah makes sense. Wish Docker made it easier to do handle that right.

**Comment by snoekieboe** [comment]
Is motion the only event being published to the MQTT broker or are there additional events? and are you planning on expanding the capabilities of this nice container?

Br

Roel

**Comment by i8beef** [comment]
Haha, yeah, thats it because its all I needed, and I wasn't really sure what other "events" would be handy to publish here. In terms of commands though, I could imagine a number of commands that it could forward to UniFi that would make sense.

Have some ideas?

**Comment by snoekieboe** [comment]
Yeah i actually do…

I use OpenHAB as my home automation solution and i base all my house settings on my “HOME STATE”.

HOME STATE is either HOME, AWAY or SLEEP.

What is would like to do is to set the camera’s  to motion based recording whilst away/sleep and stop recording when home.
As a result i would also like to see the recording state/setting published as an event towards the MQTT broker on a per camera basis.

Thanks!!
